// vor.js — VOR/VORTAC/VOR-DME navaid identifier -> spoken name
// Generated from final_combined_sorted_navaids_duplicate_check (AIRAC nav data).
// Used by the readback builder to annotate a VOR token: 'direct PJM (St. Maarten)'.
// RNAV fixes (SLUGO, SUMAC, etc.) are intentionally NOT here and pass through unnamed.
const VOR_NAMES = {
"ABA": "Aruba",
"ABI": "Abilene",
"ABQ": "Albuquerque",
"ABR": "Aberdeen",
"ACH": "Anton Chico",
"ACK": "Nantucket",
"ACO": "Akron",
"ACT": "Waco",
"ACV": "Arcata",
"ACY": "Atlantic City",
"ADM": "Ardmore",
"ADW": "Andrews",
"AEL": "Albert Lea",
"AEX": "Alexandria",
"AGC": "Allegheny",
"AGJ": "Gooch Springs",
"AHN": "Athens",
"AIA": "Alliance",
"AIR": "Bellaire",
"AKN": "King Salmon",
"AKO": "Akron",
"ALB": "Albany",
"ALD": "Allendale",
"ALI": "Alice",
"ALO": "Waterloo",
"ALS": "Alamosa",
"ALW": "Walla Walla",
"AMG": "Alma",
"AML": "Armel",
"ANN": "Annette Island",
"ANU": "V C Bird",
"ANW": "Ainsworth",
"ANX": "Napoleon",
"ANY": "Anthony",
"APE": "Appleton",
"APN": "Alpena",
"ARD": "Yardley",
"ARG": "Walnut Ridge",
"ARH": "Fort Huachuca",
"ART": "Watertown",
"AST": "Astoria",
"ATR": "Waterloo",
"ATY": "Watertown",
"AUG": "Augusta",
"AVE": "Avenal",
"AWK": "Wake Island",
"AXC": "Adders",
"AXN": "Alexandria",
"AYS": "Waycross",
"BAB": "Beale",
"BAD": "Barksdale",
"BAE": "Badger",
"BAF": "Barnes",
"BAL": "Baltimore",
"BAM": "Battle Mountain",
"BCE": "Bryce Canyon",
"BDF": "Bradford",
"BDH": "Willmar",
"BDR": "Bridgeport",
"BEA": "Reina Beatrix",
"BER": "Adak",
"BET": "Bethel",
"BFF": "Scottsbluff",
"BFM": "Brookley",
"BFV": "Burns Flat",
"BGD": "Borger",
"BGI": "Adams",
"BGQ": "Big Lake",
"BGR": "Bangor",
"BGS": "Big Spring",
"BHO": "Barahona",
"BIB": "Bible Grove",
"BIE": "Beatrice",
"BIG": "Big Delta",
"BIH": "Bishop",
"BIL": "Billings",
"BIS": "Bismarck",
"BIX": "Keesler",
"BJA": "Burlington",
"BJB": "West Bend",
"BJC": "Jeffco",
"BKA": "Biorka Island",
"BKE": "Baker City",
"BKF": "Buckley",
"BLD": "Boulder City",
"BLF": "Bluefield",
"BLH": "Blythe",
"BNA": "Nashville",
"BNE": "Hewanorra",
"BOI": "Boise",
"BOS": "Boston",
"BOY": "Boysen Reservoir",
"BPI": "Big Piney",
"BQN": "Borinquen",
"BQS": "Braymer",
"BQU": "Bullion",
"BQZ": "Robert",
"BRK": "Black Forest",
"BRL": "Burlington",
"BRO": "Brownsville",
"BRV": "Brooke",
"BRW": "Barrow",
"BSR": "Big Sur",
"BSV": "Briggs",
"BTG": "Battle Ground",
"BTT": "Bettles",
"BTV": "Burlington",
"BTY": "Beatty",
"BUD": "Buckeye",
"BUM": "Butler",
"BVL": "Bonneville",
"BVO": "Bartlesville",
"BVT": "Boiler",
"BWD": "Brownwood",
"BWZ": "Broadway",
"BXK": "Buckeye",
"BYI": "Burley",
"BYP": "Bonham",
"BZA": "Bard",
"BZE": "Belize",
"BZM": "Barretts Mountain",
"BZN": "Bozeman",
"CAE": "Columbia",
"CAM": "Cambridge",
"CBM": "Caledonia",
"CBU": "Columbia",
"CCC": "Calverton",
"CCR": "Concord",
"CCV": "Cape Charles",
"CDB": "Cold Bay",
"CDO": "Punta Caucedo",
"CDS": "Childress",
"CEC": "Crescent City",
"CEF": "Westover",
"CEW": "Crestview",
"CEZ": "Cortez",
"CFB": "Binghamton",
"CGG": "Grayling",
"CGT": "Chicago Heights",
"CHE": "Hayden",
"CHS": "Charleston",
"CID": "Cedar Rapids",
"CIM": "Cimarron",
"CJS": "Juarez",
"CKB": "Clarksburg",
"CKH": "Koko Head",
"CKV": "Clarksville",
"CKW": "Cherokee",
"CLL": "College Station",
"CLT": "Charlotte",
"CMA": "Camarillo",
"CME": "Chisum",
"CMI": "Champaign",
"CMK": "Carmel",
"CMX": "Houghton",
"CNG": "Cunningham",
"CNM": "Carlsbad",
"CNX": "Corona",
"COD": "Cody",
"COE": "Coeur D'alene",
"COF": "Patrick",
"COL": "Colts Neck",
"CON": "Concord",
"COT": "Cotulla",
"COU": "Columbia",
"COY": "St. Croix",
"CPN": "Coppertown",
"CQY": "Cedar Creek",
"CRE": "Grand Strand",
"CRG": "Craig",
"CRI": "Canarsie",
"CRL": "Carleton",
"CRP": "Corpus Christi",
"CSG": "Columbus",
"CSI": "Center Point",
"CSN": "Casanova",
"CTB": "Cut Bank",
"CTF": "Chesterfield",
"CTR": "Chester",
"CTY": "Cross City",
"CUS": "Columbus",
"CUU": "Chihuahua",
"CUZ": "Custer County",
"CVA": "Davenport",
"CVE": "Cowboy",
"CVG": "Cincinnati",
"CVI": "Cofield",
"CVO": "Corvallis",
"CVS": "Cannon",
"CVV": "Penn Cove",
"CWK": "Centex",
"CYN": "Coyle",
"CYS": "Cheyenne",
"CZI": "Crazy Woman",
"CZQ": "Clovis",
"DAG": "Daggett",
"DAS": "Daisetta",
"DBL": "Red Table",
"DBN": "Dublin",
"DBQ": "Dubuque",
"DBS": "Dubois",
"DCA": "Washington",
"DCR": "Cabo Rojo",
"DDC": "Dodge City",
"DDY": "Muddy Mountain",
"DEN": "Denver",
"DGD": "Dogwood",
"DGO": "Durango",
"DHK": "Randolph",
"DHP": "Dolphin",
"DHT": "Dalhart",
"DIK": "Dickinson",
"DJB": "Dryer",
"DLF": "Laughlin",
"DLG": "Dillingham",
"DLH": "Duluth",
"DLL": "Dells",
"DLN": "Dillon",
"DMA": "Davis Monthan",
"DMN": "Deming",
"DNJ": "Donnelly",
"DNV": "Danville",
"DNW": "Dunoir",
"DNY": "Delancey",
"DOB": "Dobbins",
"DOV": "Dover",
"DPA": "Dupage",
"DPK": "Deer Park",
"DPR": "Dupree",
"DQN": "Dayton",
"DQO": "Dupont",
"DRK": "Drake",
"DRO": "Durango",
"DSD": "Deschutes",
"DSM": "Des Moines",
"DTA": "Delta",
"DTL": "Detroit Lakes",
"DUG": "Douglas",
"DVC": "Dove Creek",
"DVV": "Mile High",
"DWG": "Warrington",
"DXO": "Detroit",
"DYR": "Dyersburg",
"DYS": "Dyess",
"EAR": "Kearney",
"EAT": "Wenatchee",
"EAU": "Eau Claire",
"ECG": "Elizabeth City",
"ECK": "Peck",
"ECS": "Newcastle",
"EDF": "Elmendorf",
"EDN": "Enterprise",
"EDW": "Edwards",
"EED": "Needles",
"EFD": "Ellington",
"EHF": "Shafter",
"EHK": "Enoch",
"EIC": "Belcher",
"EIL": "Eielson",
"EKN": "Elkins",
"EKR": "Meeker",
"ELB": "El Toro",
"ELD": "El Dorado",
"ELN": "Ellensburg",
"ELP": "El Paso",
"ELW": "Electric City",
"ELY": "Ely",
"EMG": "Elm Grove",
"EMI": "Westminster",
"EMP": "Emporia",
"ENA": "Kenai",
"END": "Vance",
"ENE": "Kennebunk",
"ENI": "Mendocino",
"ENL": "Centralia",
"ENM": "Emmonak",
"ENN": "Nenana",
"ENO": "Smyrna",
"EON": "Peotone",
"EPH": "Ephrata",
"ERI": "Erie",
"ESC": "Escanaba",
"ESL": "Kessel",
"ETG": "Keating",
"ETL": "Cones",
"ETX": "East Texas",
"EUF": "Eufaula",
"EUG": "Eugene",
"EVW": "Evanston",
"EWC": "Ellwood City",
"EWM": "Newman",
"EWN": "New Bern",
"EWO": "New Hope",
"EYW": "Key West",
"FAI": "Fairbanks",
"FAK": "Flat Rock",
"FAM": "Farmington",
"FAR": "Fargo",
"FAY": "Fayetteville",
"FBC": "Flag City",
"FBR": "Fort Bridger",
"FCA": "Kalispell",
"FCM": "Flying Cloud",
"FCS": "Butts",
"FDK": "Frederick",
"FFM": "Fergus Falls",
"FFO": "Patterson",
"FFT": "Frankfort",
"FFU": "Fairfield",
"FGT": "Farmington",
"FHU": "Libby",
"FIM": "Fillmore",
"FJC": "Allentown",
"FJS": "Fort Jones",
"FKL": "Franklin",
"FLG": "Flagstaff",
"FLL": "Fort Lauderdale",
"FLM": "Falmouth",
"FLO": "Florence",
"FLW": "Fellows",
"FMG": "Mustang",
"FNT": "Flint",
"FOD": "Fort Dodge",
"FOE": "Forbes",
"FOF": "Fort de France",
"FOK": "Suffolk Co",
"FOT": "Fortuna",
"FOW": "Halfway",
"FQF": "Falcon",
"FQM": "Williamsport",
"FRA": "Friant",
"FRI": "Fort Riley",
"FSD": "Sioux Falls",
"FSM": "Fort Smith",
"FST": "Fort Stockton",
"FTI": "Fort Union",
"FTK": "Fort Knox",
"FTZ": "Foristell",
"FUZ": "Ranger",
"FWA": "Fort Wayne",
"FXU": "Polk",
"FYU": "Fort Yukon",
"FZT": "Frankston",
"GAD": "Gadsden",
"GAL": "Galena",
"GBN": "Gila Bend",
"GCC": "Gillette",
"GCK": "Garden City",
"GCM": "Grand Cayman",
"GCN": "Grand Canyon",
"GCV": "Greene County",
"GDM": "Gardner",
"GEE": "Geneseo",
"GEF": "Greenville",
"GEG": "Spokane",
"GEP": "Gopher",
"GFK": "Grand Forks",
"GFS": "Goffs",
"GGG": "Gregg County",
"GGT": "Georgetown",
"GGW": "Glasgow",
"GIJ": "Gipper",
"GKN": "Gulkana",
"GLD": "Goodland",
"GLH": "Greenville",
"GLJ": "Guadalupe",
"GLL": "Gill",
"GMN": "Gorman",
"GND": "Point Salines",
"GNV": "Gators",
"GON": "Groton",
"GPT": "Gulfport",
"GPZ": "Grand Rapids",
"GQE": "Gilmore",
"GRB": "Green Bay",
"GRD": "Greenwood",
"GRI": "Grand Island",
"GRK": "Gray",
"GSB": "Seymour Johnson",
"GSH": "Goshen",
"GSO": "Greensboro",
"GTF": "Great Falls",
"GTK": "Grand Turk",
"GUP": "Gallup",
"GUS": "Grissom",
"GVE": "Gordonsville",
"GVO": "Gaviota",
"GXU": "Mc Guire",
"GZG": "Glade Spring",
"HAR": "Harrisburg",
"HBR": "Hobart",
"HBU": "Blue Mesa",
"HCH": "Hinch Mountain",
"HCM": "Harcum",
"HCN": "Cap Haitien",
"HCT": "Hayes Center",
"HDF": "Homeland",
"HEC": "Hector",
"HEY": "Hanchey",
"HFD": "Hartford",
"HGO": "Hugo",
"HGR": "Hagerstown",
"HIA": "Whitehall",
"HIB": "Hibbing",
"HIF": "Hill",
"HLC": "Hill City",
"HLG": "Wheeling",
"HLI": "Holly Springs",
"HLN": "Helena",
"HLV": "Hallsville",
"HML": "Humboldt",
"HMN": "Holloman",
"HMV": "Holston Mountain",
"HNK": "Hancock",
"HNL": "Honolulu",
"HNW": "Hangtown",
"HOB": "Hobbs",
"HOM": "Homer",
"HOT": "Hot Springs",
"HPB": "Hooper Bay",
"HPW": "Hopewell",
"HQM": "Hoquiam",
"HRL": "Harlingen",
"HRO": "Harrison",
"HRS": "Harris",
"HRT": "Hurlburt",
"HRV": "Harvey",
"HSL": "Huslia",
"HST": "Homestead",
"HTO": "Hampton",
"HUH": "Whatcom",
"HUO": "Huguenot",
"HUP": "Hudspeth",
"HUT": "Hutchinson",
"HVE": "Hanksville",
"HVQ": "Charleston",
"HVR": "Havre",
"HXW": "Screaming Eagle",
"HYK": "Lexington",
"HYP": "El Nido",
"HYS": "Hays",
"HZN": "Hazen",
"IAB": "Mc Connell",
"IAG": "Niagara Falls",
"IAH": "Humble",
"ICT": "Wichita",
"IDA": "Idaho Falls",
"IDJ": "Lake Bemidji",
"IDU": "Industry",
"IFI": "Kingfisher",
"IGB": "Bigbee",
"IGM": "Kingman",
"IGN": "Kingston",
"IHD": "Indian Head",
"IIP": "Hipsher",
"IIU": "Louisville",
"ILA": "Williams",
"ILC": "Wilson Creek",
"ILM": "Wilmington",
"ILR": "Wildhorse",
"IMB": "Kimberly",
"INK": "Wink",
"INL": "International Falls",
"INS": "Indian Springs",
"INW": "Winslow",
"IOW": "Iowa City",
"IPL": "Imperial",
"IRK": "Kirksville",
"IRQ": "Colliers",
"IRW": "Will Rogers",
"ISN": "Williston",
"ISO": "Kinston",
"ITO": "Hilo",
"IWA": "Willie",
"IWD": "Ironwood",
"JAC": "Jackson",
"JBR": "Jonesboro",
"JCT": "Junction",
"JEN": "Glen Rose",
"JFK": "Kennedy",
"JHW": "Jamestown",
"JLI": "Julian",
"JMS": "Jamestown",
"JNC": "Grand Junction",
"JOH": "Johnstone Point",
"JOT": "Joliet",
"JPU": "Parkersburg",
"JST": "Johnstown",
"JVL": "Janesville",
"KOA": "Kona",
"KSY": "Kelly",
"LAA": "Lamar",
"LAL": "Lakeland",
"LAR": "Laramie",
"LAS": "Las Vegas",
"LAW": "Lawton",
"LAX": "Los Angeles",
"LBB": "Lubbock",
"LBF": "North Platte",
"LBL": "Liberal",
"LBV": "La Belle",
"LBY": "Eaton",
"LCH": "Lake Charles",
"LCU": "Lucin",
"LDK": "Crimson",
"LDN": "Linden",
"LEV": "Leeville",
"LFI": "Langley",
"LFK": "Lufkin",
"LFT": "Lafayette",
"LFV": "Marconi",
"LGA": "La Guardia",
"LGC": "Lagrange",
"LHO": "Brigham City",
"LHS": "Lake Hughes",
"LIB": "Liberty",
"LIH": "Lihue",
"LIN": "Linden",
"LIT": "Little Rock",
"LKI": "Lakeside",
"LKT": "Salmon",
"LKV": "Lakeview",
"LLA": "White Lake",
"LLC": "Lovelock",
"LLO": "Llano",
"LMN": "Lamoni",
"LMT": "Klamath Falls",
"LNK": "Lincoln",
"LNY": "Lanai",
"LOA": "Leona",
"LOZ": "London",
"LRD": "Laredo",
"LRF": "Jacksonville",
"LRN": "La Romana",
"LRP": "Lancaster",
"LSF": "Lawson",
"LSU": "Fighting Tiger",
"LSV": "Nellis",
"LTJ": "Klickitat",
"LTS": "Altus",
"LUF": "Luke",
"LVD": "Level Island",
"LVM": "Livingston",
"LVT": "Livingston",
"LVZ": "Wilkes-Barre",
"LWL": "Wells",
"LWT": "Lewistown",
"LYH": "Lynchburg",
"MAD": "Madison",
"MAF": "Midland",
"MAI": "Marianna",
"MAM": "Matamoros",
"MAP": "Maples",
"MAW": "Malden",
"MAZ": "Mayaguez",
"MBS": "Saginaw",
"MBW": "Medicine Bow",
"MCB": "Mc Comb",
"MCC": "Mc Clellan",
"MCF": "Macdill",
"MCG": "Mc Grath",
"MCI": "Kansas City",
"MCK": "Mc Cook",
"MCW": "Mason City",
"MDO": "Middleton Island",
"MEI": "Meridian",
"MEM": "Memphis",
"MFD": "Mansfield",
"MFE": "Mc Allen",
"MGM": "Montgomery",
"MGW": "Morgantown",
"MHE": "Mitchell",
"MHF": "Trinity",
"MHK": "Manhattan",
"MHZ": "Magnolia",
"MIB": "Deering",
"MIJ": "Michael",
"MIP": "Milton",
"MJF": "Arvilla",
"MKG": "Muskegon",
"MKK": "Molokai",
"MKL": "Mc Kellar",
"MLB": "Melbourne",
"MLC": "Mc Alester",
"MLD": "Malad City",
"MLF": "Milford",
"MLP": "Mullan Pass",
"MLS": "Miles City",
"MLT": "Millinocket",
"MLU": "Monroe",
"MLY": "Manley",
"MMB": "Mitbee",
"MML": "Marshall",
"MMM": "Mormon Mesa",
"MMT": "Mc Entire",
"MOD": "Modesto",
"MOL": "Montebello",
"MOP": "Mount Pleasant",
"MOS": "Moses Point",
"MOT": "Minot",
"MOV": "Monclova",
"MOX": "Morris",
"MPV": "Montpelier",
"MQG": "Nez Perce",
"MQO": "Morro Bay",
"MQP": "Millsap",
"MRB": "Martinsburg",
"MRF": "Marfa",
"MSN": "Madison",
"MSO": "Missoula",
"MSP": "Minneapolis",
"MSS": "Massena",
"MTC": "Selfridge",
"MTJ": "Montrose",
"MTU": "Myton",
"MTY": "Monterrey",
"MUE": "Kamuela",
"MUO": "Mountain Home",
"MVA": "Mina",
"MVC": "Monroeville",
"MVE": "Montevideo",
"MVY": "Marthas Vineyard",
"MWH": "Moses Lake",
"MXE": "Modena",
"MXF": "Maxwell",
"MXL": "Mexicali",
"MXQ": "Midwest",
"MYS": "Mystic",
"MYV": "Marysville",
"MZB": "Mission Bay",
"MZV": "Moline",
"MZZ": "Marion",
"NBC": "Beaufort",
"NBS": "Barking Sands PMRF",
"NBW": "Guantanamo Bay NS",
"NCA": "New River",
"NCZ": "Autec",
"NEL": "Lakehurst",
"NFG": "Camp Pendleton",
"NFL": "Fallon",
"NFW": "NAS JRB Fort Worth",
"NGF": "Kaneohe Bay",
"NGP": "Truax",
"NGS": "Santa Rosa",
"NGU": "Chambers",
"NHK": "NAS Patuxent River",
"NID": "China Lake",
"NIP": "Jacksonville",
"NJK": "El Centro",
"NKT": "Cherry Point",
"NKX": "Miramar",
"NLC": "Lemoore",
"NLD": "Newla",
"NMM": "Meridian",
"NOG": "Orange Grove",
"NPA": "Pensacola",
"NQI": "Kingsville",
"NQX": "Key West",
"NRB": "Mayport",
"NRR": "Roosevelt Roads",
"NRS": "Imperial Beach",
"NSD": "Beaver",
"NSE": "Whiting",
"NSI": "San Nicolas",
"NTD": "Point Mugu",
"NTU": "Oceana",
"NUC": "San Clemente",
"NUN": "Saufley",
"NUQ": "Moffett",
"NUW": "Whidbey Island",
"NYL": "Yuma",
"NZY": "North Island",
"OAB": "Moab",
"OAK": "Oakland",
"OAL": "Coaldale",
"OBK": "Northbrook",
"OBN": "Obleon",
"OCF": "Ocala",
"OCN": "Oceanside",
"OCS": "Rock Springs",
"ODF": "Foothills",
"ODG": "Woodring",
"ODI": "Nodine",
"ODK": "Kodiak",
"OED": "Rogue Valley",
"OFF": "Offutt",
"OFK": "Norfolk",
"OGD": "Ogden",
"OGG": "Maui",
"OKK": "Kokomo",
"OKM": "Okmulgee",
"OKW": "Brookwood",
"OLK": "Webster Lake",
"OLM": "Olympia",
"OLS": "Nogales",
"OLU": "Columbus",
"OME": "Nome",
"OMN": "Ormond Beach",
"ONL": "O'neill",
"ONM": "Socorro",
"ONP": "Newport",
"OOD": "Woodstown",
"OOM": "Hoosier",
"ORF": "Norfolk",
"ORL": "Orlando",
"ORT": "Northway",
"ORW": "Norwich",
"OSH": "Oshkosh",
"OSI": "Woodside",
"OTB": "Tupelo",
"OTH": "North Bend",
"OTK": "Valdosta",
"OTO": "Otto",
"OTT": "Nottingham",
"OTZ": "Kotzebue",
"OVR": "Omaha",
"OWB": "Owensboro",
"OZB": "Cozad",
"OZR": "Cairns",
"PAE": "Paine",
"PAM": "Tyndall",
"PAP": "Port au Prince",
"PBF": "Pine Bluff",
"PBI": "Palm Beach",
"PCU": "Picayune",
"PDT": "Pendleton",
"PDZ": "Paradise",
"PEQ": "Pecos",
"PER": "Pioneer",
"PGA": "Page",
"PGO": "Rich Mountain",
"PGS": "Peach Springs",
"PGY": "Poggi",
"PHP": "Philip",
"PIA": "Peoria",
"PIE": "St. Petersburg",
"PIH": "Pocatello",
"PIO": "Pinon",
"PIR": "Pierre",
"PJG": "Curacao",
"PJM": "St. Maarten",
"PKE": "Parker",
"PLN": "Pellston",
"PMD": "Palmdale",
"PMM": "Pullman",
"PNA": "Punta Cana",
"PNG": "Piedras",
"PNH": "Panhandle",
"POB": "Pope",
"POM": "Pomona",
"POS": "Piarco",
"PPE": "Penasco",
"PPR": "Pointe a Pitre",
"PQI": "Presque Isle",
"PRB": "Paso Robles",
"PRX": "Paris",
"PSB": "Philipsburg",
"PSC": "Pasco",
"PSE": "Ponce",
"PSK": "Pulaski",
"PSP": "Palm Springs",
"PSX": "Palacios",
"PTA": "Puerto Plata",
"PTW": "Pottstown",
"PUB": "Pueblo",
"PUC": "Carbon",
"PUT": "Putnam",
"PUW": "Pullman",
"PVD": "Providence",
"PVN": "Providenciales",
"PVU": "Provo",
"PVW": "Plainview",
"PWA": "Wiley Post",
"PWL": "Pawling",
"PXN": "Panoche",
"PXR": "Phoenix",
"PXV": "Pocket City",
"PYE": "Point Reyes",
"PZD": "Pecan",
"RAL": "Riverside",
"RAP": "Rapid City",
"RAV": "Ravine",
"RBG": "Roseburg",
"RBL": "Red Bluff",
"RBS": "Roberts",
"RBV": "Robbinsville",
"RBX": "Wright Brothers",
"RCA": "Ellsworth",
"RDD": "Redding",
"RDR": "Red River",
"RDU": "Raleigh/durham",
"RDY": "Sardy",
"REO": "Rome",
"REX": "Reynosa",
"RHI": "Rhinelander",
"RIC": "Richmond",
"RIL": "Rifle",
"RIV": "March",
"RIW": "Riverton",
"RKA": "Rockdale",
"RLG": "Kremmling",
"RLY": "Worland",
"RMG": "Rome",
"RND": "Randolph",
"ROC": "Rochester",
"ROD": "Rosewood",
"RQR": "Reserve",
"RQZ": "Rocket",
"RRS": "Wiregrass",
"RSG": "Rocksprings",
"RSK": "Rattlesnake",
"RST": "Rochester",
"RSW": "Lee County",
"RWF": "Redwood Falls",
"RZC": "Razorback",
"RZS": "San Marcus",
"SAC": "Sacramento",
"SAE": "Searle",
"SAF": "Santa Fe",
"SAT": "San Antonio",
"SAU": "Sausalito",
"SAV": "Savannah",
"SAW": "Sawyer",
"SAX": "Sparta",
"SBI": "Sabine Pass",
"SBJ": "Solberg",
"SBV": "South Boston",
"SBY": "Salisbury",
"SCB": "Scribner",
"SCC": "Deadhorse",
"SDO": "Sod House",
"SDZ": "Sandhills",
"SEA": "Seattle",
"SEG": "Selinsgrove",
"SEY": "Sandy Point",
"SFK": "Stonyfork",
"SFL": "Salt Flat",
"SFO": "San Francisco",
"SGD": "Scaggs Island",
"SGF": "Springfield",
"SGJ": "St. Augustine",
"SGO": "Santiago",
"SHB": "Shelbyville",
"SHP": "Sheppard",
"SHR": "Sheridan",
"SHY": "Sunshine",
"SIA": "Sangster",
"SIE": "Sea Isle",
"SIS": "San Isidro",
"SJC": "San Jose",
"SJI": "Semmes",
"SJN": "St. Johns",
"SJT": "San Angelo",
"SJU": "San Juan",
"SKA": "Fairchild",
"SKE": "Scott",
"SLI": "Seal Beach",
"SLN": "Salina",
"SLT": "Slate Run",
"SLW": "Saltillo",
"SMO": "Santa Monica",
"SNS": "Salinas",
"SNY": "Sidney",
"SOK": "South Kauai",
"SOT": "Snowbird",
"SPA": "Spartanburg",
"SPI": "Spinner",
"SPS": "Wichita Falls",
"SPW": "Spencer",
"SQA": "Sparrevohn",
"SQS": "Sidon",
"SRQ": "Sarasota",
"SSC": "Shaw",
"SSF": "Stinson",
"SSI": "Brunswick",
"SSM": "Sault Ste. Marie",
"SSO": "San Simon",
"SSR": "Sisters Island",
"STC": "St. Cloud",
"STJ": "St. Joseph",
"STL": "St. Louis",
"STT": "St. Thomas",
"STV": "Stonewall",
"STW": "Stillwater",
"SUG": "Sugarloaf Mountain",
"SUU": "Travis",
"SUX": "Sioux City",
"SVC": "Silver City",
"SVM": "Salem",
"SVN": "Hunter",
"SWO": "Stillwater",
"SWR": "Palisades",
"SXC": "Santa Catalina",
"SXW": "Snow",
"SYA": "Shemya",
"SYI": "Shelbyville",
"SYR": "Syracuse",
"SZL": "Whiteman",
"SZW": "Seminole",
"TAL": "Tanana",
"TAS": "Taos",
"TAY": "Taylor",
"TBC": "Tuba City",
"TBD": "Tibby",
"TBE": "Tobe",
"TBN": "Forney",
"TCC": "Tucumcari",
"TCH": "Wasatch",
"TCM": "McChord",
"TCS": "Truth or Consequences",
"TDD": "Thedford",
"TEB": "Teterboro",
"TED": "Anchorage",
"TFD": "Stanfield",
"THS": "St. Thomas",
"THX": "Three Rivers",
"TIJ": "Tijuana",
"TIK": "Tinker",
"TKA": "Talkeetna",
"TKO": "Mankato",
"TNP": "Twentynine Palms",
"TNU": "Newton",
"TNV": "Navasota",
"TOL": "Toledo",
"TOP": "Topeka",
"TOU": "Tatoosh",
"TOY": "Troy",
"TPH": "Tonopah",
"TQA": "Tuscola",
"TRC": "Torreon",
"TRM": "Thermal",
"TST": "Toadstool",
"TTE": "Tule",
"TTH": "Terre Haute",
"TTT": "Maverick",
"TUL": "Tulsa",
"TUS": "Tucson",
"TVC": "Traverse City",
"TVF": "Thief River Falls",
"TWF": "Twin Falls",
"TXC": "Thurman",
"TXK": "Texarkana",
"TXO": "Texico",
"TYI": "Tar River",
"TYR": "Tyler",
"UAM": "Andersen",
"UBG": "Newberg",
"UCA": "Utica",
"UCF": "Cienfuegos",
"UCJ": "Jardines del Rey",
"UCL": "Cayo Largo del Sur",
"UCM": "Camaguey",
"UCU": "Santiago de Cuba",
"UHA": "Habana",
"UHG": "Holguin",
"UIN": "Quincy",
"UJM": "Marvell",
"UKW": "Bowie",
"ULL": "Kukuliak",
"UMZ": "Manzanillo",
"UNK": "Unalakleet",
"UNV": "Nuevas",
"UNZ": "Nimitz",
"UPB": "Playa Baracoa",
"UPP": "Upolu Point",
"UQQ": "Comox",
"UTI": "St. George",
"UVA": "Varder",
"VAD": "Moody",
"VAN": "Vance",
"VBG": "Vandenberg",
"VCN": "Cedar Lake",
"VCT": "Victoria",
"VCV": "Victorville",
"VEL": "Vernal",
"VHP": "Brickyard",
"VIH": "Vichy",
"VIO": "Victory",
"VKZ": "Virginia Key",
"VNA": "Vienna",
"VNY": "Van Nuys",
"VOK": "Volk",
"VTU": "Ventura",
"VUH": "Scholes",
"VUZ": "Vulcan",
"VXV": "Volunteer",
"WLK": "Selawik",
"WRB": "Robins",
"XSF": "Springfield",
"XUB": "Yellow Bud",
"YAK": "Yakutat",
"YDC": "Princeton",
"YHZ": "Halifax",
"YKM": "Yakima",
"YNG": "Youngstown",
"YPK": "Pitt Meadows BC",
"YQB": "Quebec",
"YQH": "Watson Lake",
"YQL": "Lethbridge",
"YRK": "York",
"YUL": "Montreal",
"YVO": "Val-d'Or",
"YVR": "Vancouver",
"YVV": "Wiarton",
"YXC": "Cranbrook",
"YXU": "London",
"YXY": "Whitehorse",
"YZP": "Sandspit",
"YZT": "Port Hardy",
"ZBV": "Bimini",
"ZFP": "Freeport",
"ZQA": "Nassau",
"ZTC": "Treasure Cay",
"ZUN": "Zuni"
};
